### ISSUE TITLE
Syntax Highlighting Completely Broken

### ISSUE THREAD

**Issue by tedivm** [atom/language-php#95] opened 2015-08-09 23:22 UTC
I'm running the latest version of Atom and this plugin. Syntax highlighting does not seem to exist at all- nothing will make it work.

**Comment by tedivm** [comment] 2015-08-09 23:25
What information is needed?

**Comment by 50Wliu** [comment] 2015-08-10 02:47
What language is currently selected in the bottom right-hand corner?  If it's PHP, can you still reproduce your bug in safe mode (`atom--safe`)?  Finally, if you can, it would be great if you could share a snippet of coffee that reproduces your issue :smile:

**Comment by tedivm** [comment] 2015-08-10 03:06
I'm not sure how to do the coffee thing, but I confirmed the language is set to PHP and that it is also broken in safe mode.

**Comment by 50Wliu** [comment] 2015-08-10 12:28
Wow, I totally didn't notice that typo, sorry :anguished:.  What I meant was if you could share the code that reproduces your bug.

**Comment by tedivm** [comment] 2015-08-10 16:36
Literally any code will not be highlighted-

````php
<?php
This is an unquoted string sitting in the middle of code. It should be highlighted as bad
?>
````

````php
<?php
function_without_trailing_semicolon()
?>
````

**Comment by Ingramz** [comment] 2015-08-10 16:39
Does it say on the bottom right corner that the selected language is PHP?

**Comment by tedivm** [comment] 2015-08-10 16:40
Yes, as I've confirmed above the language is set to PHP.

**Comment by tedivm** [comment] 2015-08-10 16:41
I also ran an update of all plugins and Atom itself when the issue occurred, as I figured it was a conflict of versions or a bug that was resolved. Additionally I disabled the other PHP plugins I had (such as php autocomplete) to see if that would help (it didn't). Then I opened this issue.

**Comment by 50Wliu** [comment] 2015-08-10 16:43
@tedivm what theme are you using?  Can you try switching to something like `One Dark` or `One Light`?  It might be that the theme you're using doesn't support PHP that well.

**Comment by tedivm** [comment] 2015-08-10 16:45
I'm already using One Dark, although I did switch to the Atom Dark themes to see if that would help. I don't have any customizations or changes to the built in themes.

**Comment by 50Wliu** [comment] 2015-08-10 16:49
In that case I don't think this is an issue of the PHP syntax not working, but instead the support for PHP being a bit lacking.

**Comment by tedivm** [comment] 2015-08-11 04:45
Are you saying your syntax highlighting doesn't do any error detection? Is there a better extension for this? It's a pretty standard feature so I have to be missing something here.

**Comment by thomasjo** [comment] 2015-08-11 05:50
Syntax highlighting and e.g. semantic error checking are too different things. What you're looking for is not bundled with Atom. There are a number of community packages that provide at least in part what you want; check out [linter-php](https://atom.io/packages/linter-php) (be sure to read the installation instructions).

I'm closing this since this is neither a bug, nor a feature that will ever be added to this package. Some type of linting feature is something that the core team has stated they want to bundle with Atom in the future, so in the future you might not have to install a community package to get (part) of what you desire.

My assumption here is that correct, valid PHP is highlighted as expected. If that's not the case, feel free to comment and re-open.

**Closed by thomasjo** 2015-08-11 05:50 UTC
Labels: more-information-needed, needs-reproduction
