### ISSUE TITLE
Textmate: Bugged syntax highlightning for a class variable when concatenating with string.

### ISSUE THREAD

**Issue by alexr00** [atom/language-php#365] opened 2019-08-09 08:49 UTC
From @min0rr in https://github.com/microsoft/vscode/issues/78767:
**Example :**
```php
<?php
const A_DBNAME = 'BROADCAST_archive';

$sql = "SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME LIKE 'zip%' AND TABLE_SCHEMA ='".ArchivationConfig::A_DBNAME."'";
?>
```
**Problem is :**
There is no syntax highlightning for constant ArchivationConfig::A_DBNAME. It is shown as a part of string. 
The token `".ArchivationConfig::A_DBNAME."` is categorized as 
string.quoted.single.sql
source.sql.embedded.php
string.quoted.double.sql.php
source.php
meta.embedded.block.php
text.html.php

**Here it is:**
![image](https://user-images.githubusercontent.com/43531018/62763906-50ccc000-ba95-11e9-86f5-f2dfe1deb03c.png)

**Comment by rsese** [comment] 2019-08-09 19:52
Thanks for contributing!

I think this looks like a duplicate of https://github.com/atom/language-php/issues/336 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-09 19:52 UTC
