### ISSUE TITLE
In the TextMate grammar a string is continuous when opened a single quote inside double quotes

### ISSUE THREAD

**Issue by alexr00** [atom/language-php#355] opened 2019-02-18 09:18 UTC
_From @gBragamonte on February 13, 2019 17:59_

Steps to Reproduce:

1. Using PHP, create a variable of type string that concat with a string function
2. Like this:

```php
$tst = "UPDATE TABLE SET ACTIVE ='S' WHERE ID IN ('" . implode("', '", [1, 2, 3]) . "')";
```

Works well but editor ignore double quote closure, see:

![image](https://user-images.githubusercontent.com/30661999/52732691-f2bc9580-2fa7-11e9-82b2-b9c45a355e89.png)

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#68644_

**Comment by Arcanemagus** [comment] 2019-02-18 22:01
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-php/issues/333. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-02-18 22:01 UTC
