### ISSUE TITLE
'Catch' with an argument (in contained Javascript)

### ISSUE THREAD

**Issue by LexLuengas** [atom/language-php#45] opened 2014-11-25 22:32 UTC
The parser doesn't seem to recognize the closing parenthesis of the argument of this (Javascript) catch statement:

![catch parenthesis bug php atom](https://cloud.githubusercontent.com/assets/3997377/5192475/10bb794e-74f8-11e4-8e09-d869e20e41bd.png)

(Notice the closing script tag is still highlighted with gray.) In TextMate the highlighting doesn't break, but as the php-grammar files of Atom and TextMate agree (compare [the first](https://github.com/atom/language-php/blob/master/grammars/php.cson#L893) and [the latter](https://github.com/textmate/php.tmbundle/blob/master/Syntaxes/PHP.plist#L1847)), I have no clue how to fix this.

**Comment by frozzare** [comment] 2015-06-27 15:07
I can't reproduce this in Atom 1.0 so it might already have been fixed. Looks like this for me.

![skarmklipp 2015-06-27 17 02 27](https://cloud.githubusercontent.com/assets/14610/8392556/b2baebd2-1cee-11e5-9e20-73b4879a6b1b.png)

**Comment by Ingramz** [comment] 2015-06-27 18:14
We keep seeing these kinds of reports in language-blade grammar too. So far most, if not all, reports are due to user error. See following picture:
![screenshot_52](https://cloud.githubusercontent.com/assets/1017132/8393262/607ba28a-1d11-11e5-8945-27cd7ab24d54.png)

**Comment by Arcanemagus** [comment] 2016-04-22 19:54
Whether this was a bug fixed by the time v1.0.0 came out, or just user error, it is no longer present so this should be closed:
![image](https://cloud.githubusercontent.com/assets/427137/14753301/4712f9a6-0889-11e6-9d30-93fdc4164960.png)

**Closed** 2016-04-22 20:17 UTC
