### ISSUE TITLE
catch highlighting doesn't work on multiple lines

### ISSUE THREAD

**Issue by ljw1004** [atom/language-php#202] opened 2017-05-30 19:17 UTC
### Description

Colorizing of PHP catch clause seems broken if the trailing close-parenthesis is on a different line:

On a different line (fails):
![image](https://cloud.githubusercontent.com/assets/3316258/26599838/e211d4da-452e-11e7-88ab-4722dabd1f52.png)

On the same line (works fine):
![image](https://cloud.githubusercontent.com/assets/3316258/26599829/d85ec43e-452e-11e7-832e-7e3f8666a1b6.png)

### Steps to Reproduce

1. Create a new file. Save it with the name "anything.php". Type in the following text:

```php
<?php

function f() {
  try {} catch (Exception $e
  ) {
      $x = 17;
    }
}

function g() {
}
```

**Expected behavior:** It should colorize the word "Exception", and also the word "function" in the declaration of g.

**Actual behavior:** Everything after the catch has completely lost all of its colorization.

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.13.0
```

OS: macOS Seirra 10.12.4

### Additional Information

Incidentally, I observe the same issue in VSCode.

**Comment by rsese** [comment] 2017-05-30 21:33
Thanks for the report!  Seems like a dupe of https://github.com/atom/language-php/issues/91?

**Comment by Ingramz** [comment] 2017-05-31 08:07
@rsese it's the same kind of issue, but #91 can be fixed in a way that leaves this issue still unsolved. So probably not duplicates, but they belong to same group of issues.

**Comment by rsese** [comment] 2017-05-31 17:56
Thanks @Ingramz, I'll go ahead and triage as a separate bug then for now then :v:

**Closed** 2017-06-09 23:41 UTC
Labels: bug
