### ISSUE TITLE
Keyword after instanceof should be given a unique scope

### ISSUE THREAD

**Issue by jens1o** [atom/language-php#225] opened 2017-06-25 09:25 UTC
### Prerequisites

* [x] I'm using vscode

### Description

![image](https://user-images.githubusercontent.com/11234139/27514948-e5c92e24-5998-11e7-93f0-ee48ff27f5c5.png)

### Steps to Reproduce

```php
<?php
// Rethrow anything that is not a RuntimeException
if (!$e instanceof RuntimeException) {
    throw $e;
}

**Comment by 50Wliu** [comment] 2017-07-09 21:51
Can't reproduce, and it does seem to work in your picture unless I'm misunderstanding something.  It's being tokenized as `keyword.operator.type.php` for me.

**Comment by jens1o** [comment] 2017-07-10 03:59
For me it gets tokenized for an `constant.other.php`...
![image](https://user-images.githubusercontent.com/11234139/28002379-ef4f6cfe-6534-11e7-9ecd-85b31b681d90.png)
@aeschli Please fix the vscode's grammar parser... :/

**Comment by 50Wliu** [comment] 2017-07-10 04:23
Oh, do you mean `RuntimeException` is being tokenized as a constant, or that `instanceof` is?  Or perhaps, what exactly do you mean by "instanceof does not work"?

**Comment by jens1o** [comment] 2017-07-10 04:30
Yes, that's what I mean, it shouldn't be a constant. Sorry, I'm in a hurry.

**Comment by 50Wliu** [comment] 2017-07-10 04:41
No problem.  What do you think it should be tokenized as then?

**Comment by jens1o** [comment] 2017-07-10 11:51
`keyword.operator.type.php`... But it's working fine for you. Maybe the vscode grammar parser has a bug?

**Comment by aidantwoods** [comment] 2017-07-27 22:39
I concur that `RuntimeException` should be a class, and not a const.

More detail: https://github.com/Microsoft/vscode/issues/30500#issuecomment-318504496

**Comment by mattacosta** [comment] 2018-03-20 04:11
I don't think that it should be under the `keyword` group. It makes more sense to keep it similar to a type that comes after the `new` keyword. So probably `support.class.php` or `support.class.instanceof.php` if necessary.

Also, this issue should be marked as a bug, since PHP never parses an `instanceof` type as a constant.

**Closed** 2020-03-26 18:29 UTC
Labels: feedback
