### ISSUE TITLE
PSR-2 class brace syntax highlighting error

### ISSUE THREAD

**Issue by JesseLeite** [atom/language-php#97] opened 2015-08-30 01:25 UTC
language-php not properly highlighting opening curly brace when following PSR-2 convention (opening curly brace on it's own line).  I tried looking through the grammar file, but I can't make sense of it to PR.

See line 13 in this example:

![example](http://i.imgur.com/3L7rbog.png)

**Comment by 50Wliu** [comment] 2015-08-30 13:57
I'll see if I can take a look at this.

**Comment by 50Wliu** [comment] 2015-08-30 15:44
Hmm...I can't reproduce this using the following example:
```php
<?php 

class NotPsrTwo {

	public function name()
	{
		//
	}

}

class PsrTwoFormatted
{
	public function name()
	{
		# code...
	}
}

```

**Comment by Ingramz** [comment] 2015-08-30 15:47
@50Wliu make sure you are using "One Dark" syntax theme

**Comment by 50Wliu** [comment] 2015-08-30 15:52
Woah, that's super weird.  I can reproduce now and I think I see the problem as well.  Thanks.

**Comment by JesseLeite** [comment] 2015-08-30 17:39
I didn't realize it was only visible on certain syntax themes.  Is the issue with language-php, or with the theme?

**Comment by 50Wliu** [comment] 2015-08-30 21:03
language-php.  In the second case the `{` is included under the `meta.class.php` scope while in the first case it isn't.

**Comment by 50Wliu** [comment] 2015-08-31 02:04
The crazy thing about this is that the scope logger seems to be ignoring `meta.class.php` - it's only visible if you actually inspect the element.  The regex also seems to be structurally sound...`(?=[;{])`.

Not even the specs are catching this!  I really don't know what to do at this point.

Images:
![devtools](https://cloud.githubusercontent.com/assets/2766036/9570869/ca3fb692-4f62-11e5-9cd7-369c2caf845d.png)
but
![scopes](https://cloud.githubusercontent.com/assets/2766036/9570875/e2269028-4f62-11e5-8ace-021eb55a27c6.png)

Test used:
```coffee
describe 'classes', ->
    it 'tokenizes them', ->
      tokens = grammar.tokenizeLines """
        <?php
        class PsrTwoFormatted
        {
        }
      """

      expect(tokens[2][0]).toEqual value: '{', scopes: ['text.html.php', 'meta.embedded.block.php', 'source.php', 'punctuation.section.scope.begin.php']

**Comment by JesseLeite** [comment] 2015-08-31 02:09
I really don't know either.  This is all a bit over my head.  Could it have anything to do with lack of multi-line `m` regex flag or something?

Ha, it's just one character... but sucks because PSR-2 is used by Symfony, Laravel, etc. so this is a very common convention in the PHP world these days.

**Comment by 50Wliu** [comment] 2015-08-31 02:11
I think `m` is enabled by default, or at least I haven't had to mess with it when doing multiline stuff in Atom.  I'll try it anyway though tomorrow morning.

**Comment by JesseLeite** [comment] 2015-08-31 02:12
Thanks for your time on this.

**Comment by Ingramz** [comment] 2015-08-31 07:21
I took a look at this as well. I could be totally wrong, but my theory is that the issue is actually with the way how lookahead behaves right now (from `'end': '(?=[;{])'`). It seems like if the characters we are looking for: `;` or `{` are the first characters on the line, then we are not exiting the current scope `meta.class.php`, but we continue our work of highlighting in a manner that we exited the scope. This doesn't leak to following lines because we're past the lookahead and some of the exiting is done automatically in the end of line. Put any character in front of the `{` or `;` and it behaves correctly.

I'll try to whip up a minimal possible grammar to see if this exists there as well, if that has the same issue, it is most likely an issue with first-mate and not with the grammar or theme.

**Comment by Ingramz** [comment] 2015-08-31 08:30
Opened atom/first-mate#56

**Comment by Ingramz** [comment] 2015-09-07 20:44
Once atom/atom#8703 from atom/atom#8701 gets merged, this issue will solve

**Comment by 50Wliu** [comment] 2015-09-11 00:11
This will be fixed in the next Atom version.  Thanks to @JesseLeite for reporting and @Ingramz for the excellent analysis :100:.

**Closed by 50Wliu** 2015-09-11 00:11 UTC
Labels: bug

**Comment by JesseLeite** [comment] 2015-09-11 00:13
Beauty, thank you both.
