### ISSUE TITLE
Opening and closing tags on the same line aren't matched.

### ISSUE THREAD

**Issue by DamnedScholar** [atom/language-php#138] opened 2016-06-01 02:52 UTC
[A thread has come up](https://discuss.atom.io/t/bug-wrong-classes-for-php-inside-js) on the forum that points out that `<?php ... ?>` doesn't get matched as PHP code when on the same line. I did a little bit of poking around and found that the embedded whitespace pattern has a negative lookahead `(?![^?]*\\?>)` that, when removed, allows single-line PHP comments to display. The thing is, I can't figure out what that negative lookahead was put there to check against. [My fork of this package](https://github.com/DamnedScholar/language-php) seems to work just fine.

Does anybody know what the negative lookahead was meant to guard against?

**Comment by 50Wliu** [comment] 2017-06-09 05:09
Unable to reproduce:
![php-single-line](https://user-images.githubusercontent.com/2766036/26961896-4ab8eaf4-4cb0-11e7-95a7-9b428f8949c1.png)

The thread you're referencing looks like a problem with PHP-in-JavaScript that was fixed in Atom 1.12.0.

**Closed by 50Wliu** 2017-06-09 05:09 UTC
Labels: bug
