### ISSUE TITLE
Mixing HTML and PHP

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#246] opened 2017-07-27 23:55 UTC
This may be covered in an issue already but I couldn't find one that hits this exact case.

If you end the PHP block inside a function body, then the HTML after it is not colorized correctly.

```php
<div>foo</div>

<?php
foo(function() {
    ?>
    <div>foo</div>
    <?php
    return "sldkfj";
});
```

![image](https://user-images.githubusercontent.com/323878/28696661-be9b0536-72eb-11e7-8326-1f21508aae2f.png)

The orange `<div>foo</div>` is still `source.php` and `meta-function-call.php`. If the function line is commented out, or if the HTML isn't inside the function body, then it is handled correctly. Would this be expected to work?

**Comment by 50Wliu** [comment] 2017-08-02 18:12
I'm curious...what is the expected output in this case?

**Comment by roblourens** [comment] 2017-08-02 19:50
This seems like a weird case, but PHP handles this, so I guess it's valid PHP?

I guess the expected result would be to have the current PHP scopes with the relevant HTML ones on top of them? It wouldn't really be possible to reset the stack at `<?` and restore all those scopes again at `<?php`, would it?

I guess I don't follow how the PHP grammar transitions from highlighting as php, to letting the HTML grammar handle it.

**Comment by hultberg** [comment] 2017-08-03 18:26
@roblourens It is valid PHP. 
```php
<?php

class MyClass
{
    protected $name = '';

    public function getName()
    {
        ?>
        <div>foo2</div>
        <?php
        return $this->name;
    }
}

$i = new MyClass;
echo $i->getName();
```
output: https://3v4l.org/0Q4pT

/cc @50Wliu

**Comment by 50Wliu** [comment] 2017-08-03 18:36
I believe @roblourens is right in that there is no way to temporarily pause the scope stack and resume it later.

**Comment by Ingramz** [comment] 2017-08-04 09:58
It might sound a little hacky but wouldn't capturing a block `?>`  `<?php` at the appropriate scope and interpreting everything between as html provide a way to continue where it left off?

**Comment by 50Wliu** [comment] 2017-08-04 14:21
Yeah, but the HTML would still receive PHP scopes such as meta.function-call.

**Comment by etiennedupuis** [comment] 2017-08-09 15:16
It's all wrong for me as well when I mix HTML and PHP in the same file.

**Comment by Ingramz** [comment] 2017-08-14 23:52
@etiennedupuis yes, that is normal (and unrelated). The green color inside HTML attribute value is inherited from the theme.

**Comment by justlevine** [comment] 2017-09-08 19:10
@roblourens - 
What version of vscode did you first see this in?
Because for me it only started in the latest update, and rolling back one version has the colors displaying correctly again.

**Comment by 50Wliu** [comment] 2017-09-08 20:51
Based on the number of issue references, it looks like this is more severe than I thought.  I'm occupied right now with other PRs, but after I finish those I'll try to swing back to this issue.

(Alternatively, someone else can try investigating and creating a PR for this!  That would be much appreciated :heart:)

**Comment by roblourens** [comment] 2017-09-08 20:59
I hadn't thought this was a regression in VS Code - I even reported it in July - but there have been quite a few reports right after our release this week. I'll take another look and try to narrow down when it might have regressed.

**Comment by roblourens** [comment] 2017-09-08 22:30
I see the problem - the original repro that I posted is not a recent regression, but there are more ways to trigger something similar now. Originally I said it was because the PHP block ends inside a function body, but really it's the function call that triggers it.

Original repro:
```php
<div>foo</div>

<?php
foo(function() {
    ?>
    <div>foo</div>
    <?php
    return "sldkfj";
});
```

New repro:
```php
<div>foo</div>

<?php
function() {
    ?>
    <div>foo</div>
    <?php
    return "sldkfj";
});
```

or even

```php
<div>foo</div>

<?php
if ($foo) {
    ?>
    <div>foo</div>
    <?php
    return "sldkfj";
});
```

Latest Atom Beta:
![image](https://user-images.githubusercontent.com/323878/30233455-86dfc646-94aa-11e7-8c08-f6954be2bc87.png)

I'm not sure whether this technically belongs in the same issue as the original one, but they seem related.

**Comment by roblourens** [comment] 2017-09-09 03:32
Seems that the problematic change is https://github.com/atom/language-php/commit/2849e4ad599e269d2d8dc32f61ef6213de738e0c. Now once you open a curly brace, you are stuck until the closing one.

![image](https://user-images.githubusercontent.com/323878/30236714-ba2ec2ac-94d4-11e7-8a30-e22b55725f7d.png)

**Comment by Ingramz** [comment] 2017-09-09 05:15
Yep, that's the one. Unfortunately the best we seemingly can do here is to revert the curly braces matching commits where adding a PHP end tag inbetween two curly braces is allowed as textmate grammars are not powerful enough to handle this case in a way that suits everyone. It could be still used in other cases.

@roblourens What's that issue you are referring to as "previous one"? I could not find it.

**Comment by roblourens** [comment] 2017-09-09 06:29
>What's that issue you are referring to as "previous one"?

The original repro at the top of this issue involves parens in a function call, and this week's repro involves curly braces. These have been introduced at different times but I see them as closely related.

**Comment by Ingramz** [comment] 2017-09-09 06:43
@roblourens ah, thanks for clarification. I guess that eliminates parenthesis matching too then.

**Comment by h-stivalet** [comment] 2017-09-09 14:41
@roblourens I confirm the same behavior in my case as shown bellow after 1.16.0 update.

This happens after opening a brace and closing PHP " { ?>" as you already mentioned. The code after the closing tag is still been scoped as PHP.

![bug](https://user-images.githubusercontent.com/16110371/30240997-bcc006b8-9540-11e7-833f-99acbcad5045.png)

Workaround. I'm being using if (): endif; in new view scripts (not my favorite syntax)

**Comment by 50Wliu** [comment] 2017-09-09 18:20
This is a tough decision to make, because I've found that recursive bracket matching is usually a prerequisite to robust syntax highlighting and autocomplete (via meta scopes).  For example, it is impossible to tell when a function ends without recursive bracket matching, or even to determine when function arguments end.

**Comment by Ingramz** [comment] 2017-09-09 22:45
@50Wliu for now there seems no other choice than go back to simply tokenizing. Getting accurate contextual information is always a plus, however if the most generic constructs get tokenized incorrectly, it remains unusable.

To make impossible things possible, we should probably start looking into a better way of controlling the scope "stack" than what textmate grammar system provides today. A very simple idea would be to perhaps allow for changing the root scopes inside begin/end rule, which could potentially fix this issue, but it's not something that I have put much thought into. After writing the previous sentence, I found that [I am not the first one to come to this conclusion](https://www.sublimetext.com/docs/3/syntax.html) (_Meta Patterns_). Please don't take it as a hint that this should be implemented in first-mate immediately as the next pull request, this is absolutely the worst thing one can do to fix this issue.

I don't want to deviate much from the issue at hand nor to be an authority on this topic, however what I am trying to say is that we should work on improving the grammar system instead and live with the compromise for now instead of having to decide between two extremes and sticking to it for the foreseeable future.

If there is any interest, I would be interested in discussing this further elsewhere. Maybe this will get the unhealthy obsession with it out of my head that I have had for well over a year now.

**Comment by 50Wliu** [comment] 2017-09-09 22:54
Oh, I am planning on reverting those rules.  Rereading my comment, it looks like I didn't make that clear at all.

There is an experimental [tree-sitter](https://github.com/tree-sitter/tree-sitter) project, but I don't know if that will solve the scope problems listed in this issue.  I'm `Wliu` on both Discuss and the Atom Slack if you'd like to continue the discussion elsewhere.

**Comment by raffjones** [comment] 2017-09-11 07:58
I am seeing something very similar and it is proving very hard to work with. I haven't made any changes to my VS Code configuration, and the theme is just the default one.

If you end a PHP block with `?>` within a function, and write some HTML for inline output, then even with the default theme, the syntax colouring is destroyed.

<img width="320" alt="screen shot 2017-09-11 at 08 57 19" src="https://user-images.githubusercontent.com/262516/30264079-405bce28-96cf-11e7-9462-a7d1c4965080.png">

**Comment by CarlosRGL** [comment] 2017-09-11 11:54
only fix for now is to stay at 1.15 version.

**Comment by roblourens** [comment] 2017-09-13 22:36
For now in VS Code, I reverted the bracket matching change for tomorrow's Insiders build.

**Comment by Ingramz** [comment] 2017-09-14 05:45
We've been working on #266 for the past day, so far everything is looking good. We are quite confident that it fixes the issues we are having and does not introduce any regressions, aiming to get it into a hotfix, but in the meanwhile it would be appreciated if anyone interested could try it out and report back.

**Closed** 2017-09-18 07:59 UTC
Labels: bug

**Comment by 50Wliu** [comment] 2017-09-19 19:18
Atom 1.20.1 and 1.21.0-beta1 have been released.
