### ISSUE TITLE
soft tabs support for php files

### ISSUE THREAD

**Issue by maltepalte** [atom/language-php#69] opened 2015-05-06 23:14 UTC
Can we please get soft tabs support for php added?  This option exists in standard Atom, but not in the language-php package, where there only seems to be hard tabs.

**Comment by lee-dohm** [comment] 2015-05-07 01:46
Soft tabs support isn't language specific. The same tab support code is applied to all languages, depending on your settings.

On your main Settings screen (which you can get to by using <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on Linux or Windows), is the "Soft Tabs" setting checked? Also, Atom tries to auto-detect whether a file is using tabs or spaces for indentation and then maintain the status quo, so if a file has tabs for indentation it will switch to hard tabs mode for that file. You can correct this by using the "Whitespace: Convert Tabs To Spaces" command in the Command Palette or my [tabs-to-spaces package](https://atom.io/packages/tabs-to-spaces). (You may have to save, close and open the file again to get the indentation setting to switch though.)

**Comment by izuzak** [comment] 2015-09-10 18:45
Closing this since no other information was provided and @lee-dohm explained things pretty well. Also, you should check out the new Tab Type config option in settings:

<img width="689" alt="screen shot 2015-09-10 at 20 44 48" src="https://cloud.githubusercontent.com/assets/38924/9797683/d725a39c-57fc-11e5-8468-39cf6eb738f2.png">

Let us know if you're still having trouble and provide more detailed steps to reproduce.

**Closed by izuzak** 2015-09-10 18:45 UTC
Labels: more-information-needed
