### ISSUE TITLE
Wrong highlight after opening string again

### ISSUE THREAD

**Issue by m1ga** [atom/language-php#37] opened 2014-09-27 13:52 UTC
![string](https://cloud.githubusercontent.com/assets/4334997/4430894/56ee5870-464d-11e4-9390-fbd5605b1012.png)

2nd line after $group." is green but it should be in the same color as groupid

Atom 132
Linux

**Comment by molteber** [comment] 2015-03-07 19:01
This bug is driving me mad. It continues down in my files making up to the rest of the file with wrong highlightning

**Comment by n0nag0n** [comment] 2016-05-26 01:53
I have problems with this as well. If I do a lot of 'some text'.$var.'more text'.$another_var...etc then the syntax randomly starts breaking in the string.

**Comment by n0nag0n** [comment] 2016-05-26 17:21
Aha, I think I figured it out.

I have this particular string in my code

`$var['element'][] = [ 'title' => $var1['title'], 'name' => 'somename['.$var1['fieldname'].']', 'type' => 'select', 'anotherField' => 'someValue', 'anotherField1' => [ 'item' => $var1['assigned_fieldname'] ], 'class' => 'someClass', 'disabled' => ($var1['anothervalue'] == true), 'another_var' => 'someother_value', 'element_value' => 'im_tired', ];` 

The text after `'class' => ` just turns grey with no highlighting. But I can get it to change if I take `'somename['.$var1['fieldname'].']'` and change it to `'somename[' . $var1['fieldname'] . ']'`. I also get different results if I reformat it with `"somename[{$var1['fieldname']}]"`

Hopefully that helps you figure out something.

**Comment by 50Wliu** [comment] 2017-06-09 02:50
Two different issues here.  The one reported by @m1ga will be fixed shortly - I believe it's due to themes incorrectly styling a meta scope that really shouldn't be there in the first place.  I will look at @n0nag0n's next.

**Comment by 50Wliu** [comment] 2017-06-09 02:57
Ok @n0nag0n your issue looks like a duplicate of https://github.com/atom/atom/issues/1667.

**Closed** 2017-06-09 03:04 UTC
Labels: bug
