### ISSUE TITLE
Wrong highlighting of regular expressions

### ISSUE THREAD

**Issue by nikolay1519** [atom/language-php#358] opened 2019-04-04 08:31 UTC
Linux Mint 19.1
Atom 1.35.1
language-php 0.44.1

1. Create PHP file
2. Paste code
```php
if (!empty($adviserModel['pseudonym'])) {
	$redirect = '/order/' . $adviserModel['pseudonym'] . '.html';
} else {
	$redirect = '/order/' . $order['adviser'] . '.html';
}

header('Location: ' . $redirect);
```

String `'/order/'` is highlighted as regular expression
![screenshot_2019-04-04 11-20-45](https://user-images.githubusercontent.com/32831131/55540502-d09fe380-56cb-11e9-84a8-9527a76f3882.png)
![screenshot_2019-04-04 11-23-23](https://user-images.githubusercontent.com/32831131/55540664-18266f80-56cc-11e9-9b6c-209d7466e9a2.png)

I don't need highlighting of regexp and SQL queries in PHP. I prefer to see them as simple strings.

I suggest to create checkboxes in language-php settings ("Disable regexp highlighting" and "Disable sql highlighting").

Thx

**Comment by Ingramz** [comment] 2019-04-05 12:21
Duplicate of #296

**Comment by Arcanemagus** [comment] 2019-04-05 17:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-php/issues/296. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-04-05 17:58 UTC
