### ISSUE TITLE
Open tag completion causes wrong tag <?<?php

### ISSUE THREAD

**Issue by mariusvw** [atom/language-php#76] opened 2015-05-23 06:14 UTC
Atom Version 0.201.0 (0.201.0) on Mac OS X

I have two things I run into when opening php tags:

**Unwanted completion**
When typing:

```
<?php
```

I'd expect to be able to press enter and go on typing, instead I have to press escape first to turn off the autocomplete window. If I don't press esc first I end up having:

```
<?<?php  ?>
```

**Wrong completion**
When typing the following:

```
<?p
```

The autocomplete window pops up as expected, when pressing enter and triggering the completion it replaces with:

```
<?<?php  ?>
```

I'd expect to get:

```
<?php ?>
```

Or maybe even better when it is on the first line of the file

```
<?php
```
This due classes mostly not having a closing PHP tag at the end of the file.

**Comment by Ingramz** [comment] 2015-05-23 22:27
A duplicate snippet with trigger `<?php` seems to fix this. The question is, should `<?` and `<?p` should also act as triggers.

**Comment by Ingramz** [comment] 2015-05-24 16:19
I also noticed something else. Typing `<?ph` suggests completion that should look something like `<??>...<?php` but it completes to `<?<?php ?>` instead. Both use trigger `php`, but in different scopes. This might be related to autocomplete+ though.

![issue](https://cloud.githubusercontent.com/assets/1017132/7788582/ad6896f8-0249-11e5-93ca-2052a4c000d6.gif)

**Comment by Ingramz** [comment] 2015-05-28 18:20
Half of the issue previously reported has been fixed by 0.203.0. Suggestions work correctly with current snippets.

Now if adding another completion with trigger `<?php`, we'd still be getting a wrong suggestion, but it completes as intended.

Also if you want, you can add this to your personal snippets for now:
```cson
'.text.html.php':
  'alternate <?php … ?>':
    'prefix': '<?php'
    'body': '<?php $0 ?>'
```

**Comment by mariusvw** [comment] 2015-05-28 18:28
Just updated to 0.204.0...

Now `<?p` completes to `<??><?php`...

The sniped works as expected.

**Comment by brendanfalkowski** [comment] 2015-05-30 04:03
Yeah, this is driving me up the wall. Hitting [return] after typing php does this:

![php-autocomplete](https://cloud.githubusercontent.com/assets/214924/7895493/419d07b4-065f-11e5-8f93-b07db7be01f3.gif)

**Closed** 2015-06-22 16:24 UTC
