### ISSUE TITLE
Syntax highlighting does not work at all for files with no html

### ISSUE THREAD

**Issue by karevn** [atom/language-php#100] opened 2015-09-14 23:20 UTC
Atom 1.0.12-something, language-php ver 29
The most simple test case:
https://gyazo.com/e045b5668837bfad44726d466f23bc58

Adding doctype makes a difference: 
https://gyazo.com/740154e148815c1011daccedbeb8e03d

Adding PHP shebang does not make it: https://gyazo.com/b573c5113419e49d03bcdc1ab0cd5189

So, I think it's a bug in "firstLineMatch" grammar regexp, but  I am not sure.

**Comment by 50Wliu** [comment] 2015-09-14 23:47
I can't reproduce this on Atom 1.0.11:
![php](https://cloud.githubusercontent.com/assets/2766036/9864573/e303eeb6-5b18-11e5-9c79-87dc59d1581d.png)

Your picture that adds `doctype` is actually not the correct colorization.  You've opened the `doctype` tag, but haven't closed it, so everything after that point is still getting tokenized as `doctype` (more specifically, `meta.tag.sgml.doctype.html`).

Can you please try reproducing this in safe mode (`atom --safe`)?  Thanks.

**Comment by karevn** [comment] 2015-09-15 05:19
It runs OK in safe mode. My next steps?

**Comment by lee-dohm** [comment] 2015-09-15 05:21
Find out which package is breaking things. Do you have Emmet installed? I'd try disabling that first if so. If not, you might try using the [package-cop package](https://atom.io/packages/package-cop) to help with the process of elimination.

**Comment by karevn** [comment] 2015-09-15 05:32
No, I don't have Emmet. Digging with package cop, I found that `highlight-selected` is causing the problem. I'll try to dig into its code and find some solution.
Thanks for helping out!

**Comment by lee-dohm** [comment] 2015-09-15 05:36
You're welcome! I'm glad I could help :grinning:

**Comment by karevn** [comment] 2015-09-15 06:39
It's totally weird, but it does not work again (and I have highlight-selected disabled now). I'll keep experimenting with it.

**Comment by karevn** [comment] 2015-09-15 06:40
It looks like it starts to work after I disable some package and reload Atom. But not when I just reload Atom.

**Comment by 50Wliu** [comment] 2017-06-09 05:03
@karevn Are you still having an issue with this?

**Comment by 50Wliu** [comment] 2018-03-05 18:02
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/language-php/issues/100#issuecomment-307296105. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2018-03-05 18:02 UTC
Labels: needs-reproduction
