### ISSUE TITLE
[php] syntax highlighting issue with strings in function parameters

### ISSUE THREAD

**Issue by aeschli** [atom/language-php#186] opened 2017-02-23 20:17 UTC
strings in function parameters are not correctly tokenized:

![invalid highlight](https://cloud.githubusercontent.com/assets/1571806/16201220/27e58a6e-36d6-11e6-8b86-2238ccca5a0d.PNG)
```php
<?php
class h {
    function test(
        string $string,
        int $flags = ENT_COMPAT | ENT_HTML401,
        string $encoding = 'ini_get("defaul_charset")',
        bool $double_encode = true): string {
        }
    )
}
```

**Comment by 50Wliu** [comment] 2017-06-09 05:14
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #178. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-06-09 05:14 UTC
Labels: bug
