### ISSUE TITLE
Bug folding PHP heredocs-style strings.

### ISSUE THREAD

**Issue by DionisiusMayr** [atom/language-php#78] opened 2015-05-26 13:09 UTC
Bug: create a function that has a heredoc string on it and a couple more lines after the end of the heredoc, then try to fold the function. It will stop at the word you used as the heredoc delimiter -since it need to be placed at the start of a line.

I'm in a hurry here so I can't upload images, but there is a better description of the bug in this post that I made yesterday:
https://discuss.atom.io/t/possible-bug-folding-php-heredocs-style-strings/17154

**Comment by 50Wliu** [comment] 2017-06-09 04:57
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/3442. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-06-09 04:57 UTC
Labels: bug
