### ISSUE TITLE
Shift + : is not working in Windows

### ISSUE THREAD

**Issue by bommell** [atom/language-php#139] opened 2016-06-01 12:59 UTC
Hi,

I've the issue that the keyboard shortcut shift + : is not working. If i want to add a : in my .php files, it always writes a >.
If i turn off the language php package everything is working fine.

**Comment by 50Wliu** [comment] 2016-06-01 13:43
This is most likely a duplicate of atom/atom-keymap#35 and atom/atom-keymap#37 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-01 13:43 UTC
