### ISSUE TITLE
Formatting Error

### ISSUE THREAD

**Issue by mikerhino** [atom/language-php#376] opened 2019-12-09 18:28 UTC
Coding php, if you put 'AND (' in a string, Atom styles everything after as if the quotes are still opened.

<img width="777" alt="Screen Shot 2019-12-09 at 1 28 11 PM" src="https://user-images.githubusercontent.com/54284618/70461921-c9657c80-1a87-11ea-9097-12211e7db105.png">

**Comment by Arcanemagus** [comment] 2019-12-09 19:08
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-php/issues/333. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-12-09 19:08 UTC
