### ISSUE TITLE
Support trait overwrites

### ISSUE THREAD

**Issue by jens1o** [atom/language-php#200] opened 2017-05-18 19:03 UTC
![image](https://cloud.githubusercontent.com/assets/11234139/26219002/6d9705be-3c0d-11e7-979b-015ea089ca0b.png)

Code: 
```php
<?php
trait A {
    public function smallTalk() {
        echo 'a';
    }
    public function bigTalk() {
        echo 'A';
    }
}

trait B {
    public function smallTalk() {
        echo 'b';
    }
    public function bigTalk() {
        echo 'B';
    }
}

class Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
    }
}

class Aliased_Talker {
    use A, B {
        B::smallTalk insteadof A;
        A::bigTalk insteadof B;
        B::bigTalk as talk;
    }
}

**Comment by 50Wliu** [comment] 2017-06-09 05:16
This looks like a duplicate of #127.  Please correct me if I'm wrong.

**Closed by 50Wliu** 2017-06-09 05:16 UTC

**Comment by jens1o** [comment] 2017-06-13 07:39
Yes, it is. Thanks!
