### ISSUE TITLE
PHP EOP, xml content

### ISSUE THREAD

**Issue by MaksOuw** [atom/language-php#155] opened 2016-09-22 13:50 UTC
In PHP, when using <<<EOP var type with XML content, the syntax colorization is not right. See screenshot, line 237 (in the screenshot).

It's because of the XML first line declaration, which is endded with "?>", which is the PHP closing tag too. When I remove it, the syntax color is OK.

As you can see too, if there's underscore char in XML tag, the whole word after the underscore, with the closing tag, is not colorized (see <masque_saisie> and <masque_rendu> on the screen, line 239-240)

![capture du 2016-09-22 15-47-35](https://cloud.githubusercontent.com/assets/4067614/18750581/06d4dcc6-80dc-11e6-99d1-02af4e024541.png)

**Comment by Ingramz** [comment] 2016-09-22 15:02
@50Wliu this is a duplicate of other heredoc-not-working issues.

**Comment by 50Wliu** [comment] 2016-09-22 15:27
Looks like this is a duplicate of #57 then.

**Closed by 50Wliu** 2016-09-22 15:27 UTC
Labels: bug
