### ISSUE TITLE
Method calls in strings (string parsing) are incorrectly highlighted.

### ISSUE THREAD

**Issue by ghost** [atom/language-php#109] opened 2015-11-06 19:54 UTC
Hello

Currently variables inside double quoted strings are correctly highlighted:

``` php
$string = "
    Do {$this->test} this.
";
```

However, the syntax highlighting becomes somewhat awkward when turning it into a method call:

``` php
$string = "
    Do {$this->test()} this.
";
```

`test()` is then suddenly highlighted as the rest of the string instead of in a different color.

Thanks in advance

**Comment by zr9** [comment] 2016-01-19 00:07
I'm suppose it cannot be fixed right now.
There is 2 bugs at once, 1st one is atom itself, 2nd one is grammar.

For first one, usually themes have "function-call" scope is same as text color, so not specially styled, and due to css priority "string" CSS rules get over global one, it partially solvable by theme styles like for example in my theme it different.

Without "funciton-call" scope style:
![atom_isse_1](https://cloud.githubusercontent.com/assets/13107923/12405888/0684aa4e-be59-11e5-9cc0-5d5fc5111611.png)

With "funciton-call" scope style:
![atom_isse_2](https://cloud.githubusercontent.com/assets/13107923/12405891/0a2620ec-be59-11e5-8298-46aa2fb64f55.png)

That is the first problem. 2nd one is issue #47. Currently grammar not have parenthesis as scope, that one can be fixed in future, but notice **comma** color on 2nd screen, that and probably other things still be a problem even if issue #47 solved.

**Comment by 50Wliu** [comment] 2016-01-19 00:46
I've been noticing many grammars don't have any punctuation support (like in this example, I'm seeing `=`, `"`, `,`, and `;` all aren't highlighted).  Takes a surprisingly large amount of effort to get them highlighted too, especially the longer the language goes without support.

**Comment by zr9** [comment] 2016-01-19 01:09
Technically grammar can has support punctuation, it take time but possible. Problem is in CSS, basically not a problem, but it just they way CSS works, until themes for atom not cover scopes explicitly there is always be kind of that problem in all languages, because top scope rule get priority except lower is explicitly set, so i'm suggest to set this one to "wont fix" or to wont fix with reference to issue and explanation for themes if it possible.

**Comment by Arcanemagus** [comment] 2016-04-22 20:18
Looks like this is the same bug as #61, just much better documented. That should probably be closed as a duplicate of this.

**Closed** 2017-06-09 23:41 UTC
Labels: bug
