### ISSUE TITLE
atom - auto indentation issue - switch statement

### ISSUE THREAD

**Issue by riccardobosini** [atom/language-php#294] opened 2017-11-01 13:32 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Wrong auto indentation using switch statements with IF characters inside the text of a case sentence.

### Steps to Reproduce

1. Open the code attached.
2. Copy it and paste it in Atom.
3. Save it like a php file.
4. Execute an auto indentation.
5. Look at both switch statements.
6. Notice that if the case sentence contains a 'if' characters the auto-indentation goes wrong.

**Expected behavior:** [What you expect to happen]

A correct auto-indentation

**Actual behavior:** [What actually happens]

A wrong auto-indentation

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

Each version

### Additional Information

None

[atom_issue.txt](https://github.com/atom/language-php/files/1434262/atom_issue.txt)

**Comment by Arcanemagus** [comment] 2019-06-14 16:40
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-php/issues/130. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-14 16:40 UTC
