### ISSUE TITLE
No highlights inside HTML tags

### ISSUE THREAD

**Issue by TamasDukai** [atom/language-php#144] opened 2016-07-08 16:39 UTC
Hi,

The syntax of my php code isn't highlighted inside <html></html>

**Comment by joshvickerson** [comment] 2016-07-13 21:41
Duplicate of #115?

**Comment by 50Wliu** [comment] 2016-07-15 01:06
There is currently not enough information to triage this issue.  @TamasDukai please read [How Do I Submit a (Good) Bug Report?](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) and then file a new issue.

**Closed by 50Wliu** 2016-07-15 01:06 UTC
