### ISSUE TITLE
Incorrect class bracket and param type coloring in Atom v1.20.0

### ISSUE THREAD

**Issue by philraj** [atom/language-php#270] opened 2017-09-14 00:27 UTC
As seen here, the opening bracket of the class definition and the closing bracket of the first function are colored incorrectly, and so are the types in the function parameters (they should have the same color as class names, which is yellow in this theme).

![screen shot 2017-09-13 at 8 22 00 pm](https://user-images.githubusercontent.com/16470658/30406702-73d8aaca-98c1-11e7-8bcb-a96f9f5b29c5.png)

**Comment by Ingramz** [comment] 2017-09-14 05:53
Duplicate of #268 #267 #265

**Closed** 2017-09-14 08:06 UTC

**Comment by philraj** [comment] 2017-09-19 19:47
The latest update didn't fix the second problem I mention in this issue.
