### ISSUE TITLE
PHP syntax not being applied if opening tag precedes HTML on same line

### ISSUE THREAD

**Issue by Alhadis** [atom/language-php#74] opened 2015-05-18 05:33 UTC
Well, this is an odd one:

![figure-a](https://cloud.githubusercontent.com/assets/2346707/7674764/1a7252b6-fd72-11e4-9f9e-49bcac2c8095.png)

Atom's developer tools show the line being parsed like this:

![figure-b](https://cloud.githubusercontent.com/assets/2346707/7674802/a2f5dd2e-fd72-11e4-97d8-1bafdce24999.png)

As you can see, `?php` isn't even being recognised as a starting token unless there's at least one whitespace character before it.

**Comment by PaulMorel** [comment] 2015-05-19 18:33
I can confirm I have the same issue on Atom 0.199.0 on Mac OS X 10.9.1.

Here's a quick example with Wordpress fucntions.

![screen shot 2015-05-19 at 2 30 02 pm](https://cloud.githubusercontent.com/assets/1200261/7710741/cd326186-fe33-11e4-935a-22b544ed21e2.png)

**Comment by stevekirkby** [comment] 2015-05-25 13:00
Similar in Atom 0.201 on OSX 10.10.3

**Comment by PaulMorel** [comment] 2015-05-28 18:09
I think this was fixed in Atom 0.203.0 as I can't reproduce the error anymore. 

I believe this issue in the changelog was the cause of our problems.

> Fixed an issue where editor tokens were not properly matching scope selectors

**Comment by 50Wliu** [comment] 2015-05-28 18:25
@PaulMorel it was actually fixed in 0.202.0 (thanks to this commit: https://github.com/atom/language-html/commit/3a9bedebfa26d916488df45e99ce536b7abdfff4).  Thanks though!

**Closed by 50Wliu** 2015-05-28 18:25 UTC

**Comment by Alhadis** [comment] 2015-06-03 00:41
Yes, confirmed it's no longer a problem! :D Thank you! ^_^;
