### ISSUE TITLE
"?>" not ignored inside a heredoc

### ISSUE THREAD

**Issue by Wardevour** [atom/language-php#189] opened 2017-03-28 23:59 UTC
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Can we ignore "?>" inside a heredoc? When trying to put xml in one, I lose syntax highlighting.

### Steps to Reproduce

```php
<?php
$xmlstr = <<<XML
<?xml version="1.0" encoding="UTF-8"?>

<element
  attribute="foobar"
>

</element>
XML;

echo "this line has no syntax highligting :(";
```

**Expected behavior:**
the last line to have color

**Actual behavior:** 
everything but the last line has color

**Reproduces how often:**
all the time

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Ubuntu GNOME 14.04.5 LTS 
3.19.0-80-generic

**Comment by rsese** [comment] 2017-03-29 02:03
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/language-php/issues/10 - it also looks like a fix was merged in https://github.com/atom/language-php/pull/184 with an ETA of 1.17.0 for the fix to be available /cc https://github.com/atom/language-php/pull/184#issuecomment-286563230.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-29 02:03 UTC
